# Generated by Django 3.1.4 on 2020-12-10 21:54

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('le_id', models.CharField(max_length=8)),
                ('english', models.CharField(max_length=36)),
                ('county', models.CharField(max_length=9)),
                ('guid', models.CharField(max_length=36)),
                ('pop2016', models.IntegerField()),
                ('c19_p14_t', models.CharField(max_length=17)),
                ('p14_100k', models.FloatField()),
                ('p14_100k_t', models.CharField(max_length=17)),
                ('ire_incp14', models.IntegerField()),
                ('eventdate', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ireland.profile')),
            ],
        ),
    ]
